#!/bin/bash

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'

function con() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "        CEK USAGE QUOTA AKUN TROJAN      "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"

# Mengambil daftar akun
data=( `grep '^#!' /etc/xray/config.json | cut -d ' ' -f 2 | sort | uniq` )

for akun in "${data[@]}"; do
    if [[ -z "$akun" ]]; then
        akun="tidakada"
    fi
    
    byte=$(cat /etc/trojan/${akun}) 2>/dev/null
    if [[ -z "$byte" ]]; then
        byte=0
    fi
    
    usage_quota=$(con $byte)
    
    # Mendapatkan limit kuota dari file yang sesuai
    lim=$(cat /etc/limit/trojan/${akun}) 2>/dev/null
    if [[ -z "$lim" ]]; then
        lim=0
    fi
    limit_quota=$(con $lim)

    echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
    printf "    %-13s %-7s\n" "UserName : ${akun}"
    printf "    %-13s %-7s\n" "Usage Quota : ${usage_quota}" 
    printf "    %-13s %-7s\n" "Limit Quota : ${limit_quota}" 
    echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
done

echo ""
read -p "ENTER UNTUK KEMBALI KE MENU"
menu
