#!/bin/bash

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'

function con() {
    local -i bytes=$1;
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}
clear

echo -n > /tmp/other.txt
data=( `cat /etc/xray/config.json | grep '^#!' | cut -d ' ' -f 2 | sort | uniq`);
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "          CEK LOGIN AKUN TROJAN           "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
for akun in "${data[@]}"
do
if [[ -z "$akun" ]]; then
akun="tidakada"
fi
echo -n > /tmp/iptrojan.txt
# Ambil semua IP yang terkait dengan akun tersebut
data2=( `cat /var/log/xray/access.log | grep "$akun" | awk '{print $3}' | cut -d ':' -f 1 | sort | uniq`);

# Proses setiap IP yang ditemukan
for ip in "${data2[@]}"
do
# Cek apakah IP ini benar-benar terkait dengan akun yang sedang diperiksa
jum=$(cat /var/log/xray/access.log | grep -w "$akun" | grep "$ip" | awk '{print $3}' | cut -d ':' -f 1 | sort | uniq)

# Jika ditemukan, simpan ke dalam file sementara
if [[ "$jum" = "$ip" ]]; then
echo "$jum" >> /tmp/iptrojan.txt
else
echo "$ip" >> /tmp/other.txt
fi

done

# Tampilkan hasil pengecekan login IP untuk akun ini
jum=$(cat /tmp/iptrojan.txt | sort | uniq)
if [[ -z "$jum" ]]; then
echo > /dev/null
else
iplimit=$(cat /etc/kyt/limit/trojan/ip/${akun})
jum2=$(cat /tmp/iptrojan.txt | wc -l)
byte=$(cat /etc/trojan/${akun})
lim=$(con ${byte})
wey=$(cat /etc/limit/trojan/${akun})
gb=$(con ${wey})
lastlogin=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | awk '{print $2}' | tail -1)
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
printf "    %-13s %-7s %-8s %2s\n" "  UserName : ${akun}"
printf "    %-13s %-7s %-8s %2s\n" "  Login    : $lastlogin"
printf "    %-13s %-7s %-8s %2s\n" "  Usage Quota : ${gb}" 
printf "    %-13s %-7s %-8s %2s\n" "  Limit Quota : ${lim}" 
printf "    %-13s %-7s %-8s %2s\n" "  Limit IP : $iplimit" 
printf "    %-13s %-7s %-8s %2s\n" "  Login IP : $jum2" 
printf "    %-13s %-7s %-8s %2s\n" "  IPs : $jum" 
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
fi 
rm -rf /tmp/iptrojan.txt
done
rm -rf /tmp/other.txt
echo ""
read -p "ENTER UNTUK KEMBALI KE MENU"
menu
