#!/bin/bash

RED='\033[0;31m'
NC='\033[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'
GREEN='\033[0;32m'
LIGHT='\033[0;37m'

# Getting IP (if needed)
MYIP=$(wget -qO- ipinfo.io/ip);
clear

# Header
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo "      PENGGUNA          DATA EXP          "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"

# List users and expiration dates
USER_LIST=()
while read expired
do
  AKUN="$(echo $expired | cut -d: -f1)"
  ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
  exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
  status="$(passwd -S $AKUN | awk '{print $2}' )"

  if [[ $ID -ge 1000 ]]; then
    if [[ "$status" = "L" ]]; then
      printf "%-17s %2s %-17s %2s \n" "  $AKUN"  "     $exp (Locked)"
    else
      printf "%-17s %2s %-17s %2s \n" "  $AKUN"  "     $exp"
    fi
    USER_LIST+=("$AKUN")
  fi
done < /etc/passwd

# Show number of users
JUMLAH="${#USER_LIST[@]}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "     Account number: $JUMLAH   user"
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e ""

# Ask to view details of a specific account
echo -e "Masukkan nomor akun untuk melihat detailnya, atau tekan ENTER untuk kembali ke menu:"
for i in "${!USER_LIST[@]}"; do
  echo "$((i+1)). ${USER_LIST[$i]}"
done

read -p "Pilih nomor akun: " choice

if [[ -n $choice && $choice -ge 1 && $choice -le $JUMLAH ]]; then
  selected_user="${USER_LIST[$((choice-1))]}"
  echo -e "${Lgreen}Informasi Detail untuk User: $selected_user${NC}"
  grep "^$selected_user:" /etc/passwd | awk -F: '
  { 
    print "Username   : " $1;
    print "UID        : " $3;
    print "GID        : " $4;
    print "Home Dir   : " $6;
    print "Shell      : " $7;
  }'
  
  exp="$(chage -l $selected_user | grep "Account expires" | awk -F": " '{print $2}')"
  echo "Expiration : $exp"
  status="$(passwd -S $selected_user | awk '{print $2}')"
  echo "Status     : $status"
else
  echo "Kembali ke menu."
fi

read -n 1 -s -r -p " ENTER UNTUK KEMBALI KE MENU"
m-sshws
