#!/bin/bash

# Ambil tanggal dari server
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")
NC="\e[0m"
Lgreen='\033[92m'
PURPLE='\033[35m'

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         DAFTAR AKUN VMESS          "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"

# Ambil daftar klien
clients=$(grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort -u)
NUMBER_OF_CLIENTS=$(echo "$clients" | wc -l)

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo "Anda tidak memiliki klien yang ada!"
    exit 1
fi

echo -e "$clients" | nl -s ') '

read -rp "Pilih Klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

# Validasi input
if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then
    echo "Input tidak valid. Kembali ke menu Vmess..."
    exit 1
fi

selected_client=$(echo "$clients" | sed -n "${CLIENT_NUMBER}p")
user=$(echo "$selected_client" | cut -d ' ' -f 1)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)
domain=$(cat /etc/xray/domain)

# JSON untuk VMESS
acs=$(cat <<EOF
{
  "v": "2",
  "ps": "${user}",
  "add": "${domain}",
  "port": "443",
  "id": "${uuid}",
  "aid": "0",
  "net": "ws",
  "path": "/vmess",
  "type": "none",
  "host": "${domain}",
  "tls": "tls"
}
EOF
)

ask=$(cat <<EOF
{
  "v": "2",
  "ps": "${user}",
  "add": "${domain}",
  "port": "80",
  "id": "${uuid}",
  "aid": "0",
  "net": "ws",
  "path": "/vmess",
  "type": "none",
  "host": "${domain}",
  "tls": "none"
}
EOF
)

# Encode VMESS link
vmesslink1="vmess://$(echo "$acs" | base64 -w 0)"
vmesslink2="vmess://$(echo "$ask" | base64 -w 0)"

# Tampilkan informasi akun VMESS
clear
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» INFORMASI AKUN « "
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» Domain      : ${domain}"
echo -e "» Pengguna    : ${user}" 
echo -e "» ID          : ${uuid}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» VMESS TLS"
echo -e "${vmesslink1}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» VMESS NON TLS"
echo -e "${vmesslink2}"

echo -e "» Tanggal Exp  : ${exp}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"

read -n 1 -s -r -p "Tekan Enter untuk kembali ke menu"
menu
