#!/bin/bash

# Mendapatkan tanggal dari server
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")

clear

# Filter untuk klien TrojanWS saja dari file config.json
NUMBER_OF_CLIENTS=$(grep -c -E "^#! trojanws" "/etc/xray/config.json")

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "Anda tidak memiliki klien TrojanWS yang ada!"
    exit 1
fi

clear
echo "TAMPILKAN INFORMASI AKUN TROJAN WS"
echo "Silakan pilih klien yang ingin ditampilkan informasinya"
echo "==============================="
grep -E "^#! trojanws" "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '

# Memilih klien
read -rp "Pilih klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

# Jika input kosong, kembali ke menu trojan 
if [[ -z "$CLIENT_NUMBER" ]]; 
then m-trojan 
exit 0 
fi 
# Jika input tidak valid 
if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then 
    echo "Input tidak valid. Kembali ke menu Trojan..." 
    m-trojan 
    exit 1 
fi

# Mendapatkan informasi klien berdasarkan pilihan
domain=$(cat /etc/xray/domain)
user=$(grep -E "^#! trojanws" "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#! trojanws" "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)

# Tampilkan informasi akun TrojanWS
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\\E[40;1;37m        Informasi Akun Trojan WS       \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "Nama Pengguna   : ${user}"
echo -e "Domain          : ${domain}"
echo -e "ID              : ${uuid}"
echo -e "Batas Waktu     : ${exp}"
echo -e "Port TLS        : 443"
echo -e "TROJAN TLS      : trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
echo -e "TROJAN NTLS     : trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

echo ""

read -n 1 -s -r -p "Tekan tombol apa saja untuk kembali ke menu"
menu
