#!/bin/bash

dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")

clear

# Mengambil daftar klien
clients=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort -u)

# Jumlah klien 
NUMBER_OF_CLIENTS=$(echo "$clients" | wc -l)

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "Anda tidak memiliki klien yang ada!"
    exit 1
fi

clear
echo "TAMPILKAN INFORMASI AKUN XRAY TROJAN"
echo "Silakan pilih klien yang ingin ditampilkan informasinya"
echo "==============================="

echo "$clients" | nl -s ') '

read -rp "Pilih klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

if [[ -z "$CLIENT_NUMBER" ]]; then
    m-trojan
    exit 0
fi

if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then
    echo "Input tidak valid. Kembali ke menu Trojan..."
    m-trojan
    exit 1
fi

selected_client=$(echo "$clients" | sed -n "${CLIENT_NUMBER}p")
user=$(echo "$selected_client" | cut -d ' ' -f 1)
exp=$(echo "$selected_client" | cut -d ' ' -f 2)

# Mendapatkan UUID dari file config.json berdasarkan email (user)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)

domain=$(cat /etc/xray/domain)

# Tampilkan informasi akun TrojanWS
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\\E[40;1;37m        Informasi Akun Xray/Vmess        \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "Nama Pengguna   : ${user}"
echo -e "Domain          : ${domain}"
echo -e "ID              : ${uuid}"
echo -e "Batas Waktu     : ${exp}"
echo -e "TROJAN TLS      : trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
echo -e "TROJAN NTLS     : trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""

read -n 1 -s -r -p "Tekan tombol apa saja untuk kembali ke menu"
menu
