#!/bin/bash

dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")
NC="\e[0m"
Lgreen='\033[92m'
PURPLE='\033[35m'

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         DAFTAR AKUN VMESS          "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
clients=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort -u)
NUMBER_OF_CLIENTS=$(echo "$clients" | wc -l)

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "Anda tidak memiliki klien yang ada!"
    exit 1
fi

clear
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         DAFTAR AKUN VMESS          "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "$clients" | nl -s ') '
echo -e "${PURPLE}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
read -rp "Pilih Klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

if [[ -z "$CLIENT_NUMBER" ]]; then
    m-vmess
    exit 0
fi

if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then
    echo "Input tidak valid. Kembali ke menu Vmess..."
    m-vmess
    exit 1
fi

selected_client=$(echo "$clients" | sed -n "${CLIENT_NUMBER}p")
user=$(echo "$selected_client" | cut -d ' ' -f 1)
exp=$(echo "$selected_client" | cut -d ' ' -f 2)

# Mendapatkan UUID dari file config.json berdasarkan email (user)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)
domain=$(cat /etc/xray/domain)

# JSON config untuk VMESS
acs=$(cat <<EOF
{
  "v": "2",
  "ps": "${user}",
  "add": "${domain}",
  "port": "443",
  "id": "${uuid}",
  "aid": "0",
  "net": "ws",
  "path": "/vmess",
  "type": "none",
  "host": "${domain}",
  "tls": "tls"
}
EOF
)

ask=$(cat <<EOF
{
  "v": "2",
  "ps": "${user}",
  "add": "${domain}",
  "port": "80",
  "id": "${uuid}",
  "aid": "0",
  "net": "ws",
  "path": "/vmess",
  "type": "none",
  "host": "${domain}",
  "tls": "none"
}
EOF
)

grpc=$(cat <<EOF
{
  "v": "2",
  "ps": "${user}",
  "add": "${domain}",
  "port": "443",
  "id": "${uuid}",
  "aid": "0",
  "net": "grpc",
  "path": "vmess-grpc",
  "type": "none",
  "host": "${domain}",
  "tls": "tls"
}
EOF
)

# Encode JSON dan tautan VMESS ke base64
vmesslink1="vmess://$(echo "$acs" | base64 -w 0)"
vmesslink2="vmess://$(echo "$ask" | base64 -w 0)"
vmesslink3="vmess://$(echo "$grpc" | base64 -w 0)"

# Restart layanan
systemctl restart xray > /dev/null 2>&1
service cron restart > /dev/null 2>&1

# Tampilkan informasi akun VMESS
clear
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» INFORMASI AKUN « "
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» Domain      : ${domain}"
echo -e "» Pengguna    : ${user}" 
echo -e "» Port TLS    : 443"
echo -e "» Port NTLS   : 80, 8080, 8880, 2082"
echo -e "» ID         : ${uuid}"
echo -e "» AlterID    : 0"
echo -e "» Security    : auto"
echo -e "» Network     : ws"
echo -e "» Path        : /vmess/multi-path"
echo -e "» ServiceName  : vmess-grpc"
echo -e "» Tanggal Exp  : ${exp}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» VMESS TLS"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "${vmesslink1}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» VMESS NON TLS"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "${vmesslink2}"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "» VMESS GRPC"
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}"
echo -e "${vmesslink3}"
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}"

read -n 1 -s -r -p "Tekan Enter untuk kembali ke menu"
menu
