#!/bin/bash

# Mendapatkan tanggal dari server
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")

clear

# Jumlah klien
NUMBER_OF_CLIENTS=$(grep -c -E "^#! " "/etc/xray/config.json")

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "Anda tidak memiliki klien yang ada!"
    exit 1
fi

clear
echo "TAMPILKAN INFORMASI AKUN XRAY VMESS"
echo "Silakan pilih klien yang ingin ditampilkan informasinya"
echo "==============================="
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '

# Memilih klien
read -rp "Pilih klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

if [[ -z "$CLIENT_NUMBER" ]]; then
    menu_trojan
    exit 0
fi

if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then
    echo "Input tidak valid. Kembali ke menu Trojan..."
    menu_trojan
    exit 1
fi

# Mendapatkan informasi klien
domain=$(cat /etc/xray/domain)
user=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)

# Tampilkan informasi akun
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\\E[40;1;37m        Informasi Akun Xray/Vmess        \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "Nama Pengguna   : ${user}"
echo -e "Domain          : ${domain}"
echo -e "ID              : ${uuid}"
echo -e "Batas Waktu     : ${exp}"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

echo ""

# Memeriksa dan menghapus duplikat
dupes=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2 | sort | uniq -d)

for user_dup in $dupes; do
    # Menghapus semua entri duplikat kecuali yang pertama
    sed -i "0,/^#! $user_dup/! s/^#! $user_dup/#DUPLICATE/" "/etc/xray/config.json"
done

# Menghapus baris yang ditandai sebagai duplikat
sed -i '/#DUPLICATE/d' "/etc/xray/config.json"

# Kembali ke menu setelah menampilkan informasi
read -n 1 -s -r -p "Tekan tombol apa saja untuk kembali ke menu"
menu
