#!/bin/bash

# Mendapatkan tanggal dari server
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=$(date +"%Y-%m-%d" -d "$dateFromServer")

clear

# Mengambil daftar klien Vmess, mengurutkan, dan menghilangkan duplikat
clients=$(grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort -u)

# Jumlah klien setelah diurutkan dan dihilangkan duplikat
NUMBER_OF_CLIENTS=$(echo "$clients" | wc -l)

if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    clear
    echo "Anda tidak memiliki klien yang ada!"
    exit 1
fi

clear
echo "TAMPILKAN INFORMASI AKUN XRAY VMESS"
echo "Silakan pilih klien yang ingin ditampilkan informasinya"
echo "==============================="

# Menampilkan daftar klien dengan nomor urut
echo "$clients" | nl -s ') '

# Memilih klien
read -rp "Pilih klien [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER

# Jika input kosong, kembali ke menu Vmess
if [[ -z "$CLIENT_NUMBER" ]]; then
    m-vmess
    exit 0
fi

# Jika input tidak valid
if ! [[ "$CLIENT_NUMBER" =~ ^[0-9]+$ ]] || [[ "$CLIENT_NUMBER" -lt 1 ]] || [[ "$CLIENT_NUMBER" -gt "$NUMBER_OF_CLIENTS" ]]; then
    echo "Input tidak valid. Kembali ke menu Vmess..."
    m-vmess
    exit 1
fi

# Mendapatkan informasi klien yang dipilih
selected_client=$(echo "$clients" | sed -n "${CLIENT_NUMBER}p")
user=$(echo "$selected_client" | cut -d ' ' -f 1)
exp=$(echo "$selected_client" | cut -d ' ' -f 2)

# Mendapatkan UUID dari file config.json berdasarkan email (user)
uuid=$(grep -E "\"email\": \"${user}\"" "/etc/xray/config.json" | cut -d '"' -f 4 | head -n 1)

# Mengambil domain
domain=$(cat /etc/xray/domain)

# Tampilkan informasi akun Vmess
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\\E[40;1;37m        Informasi Akun Xray/Vmess        \E[0m"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "Nama Pengguna   : ${user}"
echo -e "Domain          : ${domain}"
echo -e "ID              : ${uuid}"
echo -e "Batas Waktu     : ${exp}"
echo -e "» VMESS TLS" 
echo -e "◈━━━━━◈◈━━━━━◈" 
echo -e "vmess://"${uuid}@${domain}:443?security=tls&host=${domain}#${user}" | base64 
echo -e "◈━━━━━◈◈━━━━━◈"
echo -e "» VMESS NON TLS" 
echo -e "◈━━━━━◈◈━━━━━◈" 
echo -e "vmess://"${uuid}@${domain}:80#${user}" | base64 
echo -e "◈━━━━━◈◈━━━━━◈"
echo -e "\e[33m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo ""

# Kembali ke menu
read -n 1 -s -r -p "Tekan tombol apa saja untuk kembali ke menu"
menu
