#!/bin/bash

RED="\033[31m"
YELLOW="\033[33m"
NC='\e[0m'
Lgreen='\033[92m'
PURPLE='\033[35m'
YELL='\033[0;33m'
BRED='\033[1;31m'
GREEN='\033[0;32m'
ORANGE='\033[33m'
BGWHITE='\e[0;100;37m'

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/welwel11/izin/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "\033[1;93m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    exit 0
  fi
}
checking_sc
clear

domain=$(cat /etc/xray/domain)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "         BUAT AKUN VLESS   "
echo -e "${Lgreen}◈━━━━━━━━━━━━━━━━━◈◈━━━━━━━━━━━━━━━━━◈ ${NC}"
echo -e "${PURPLE}◈━━━━◈◈━━━━◈ ${NC}"

  read -rp " Pengguna : " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

if [[ ${CLIENT_EXISTS} == '1' ]]; then
  clear
  echo -e " ${NC} ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e " ${NC} ${BGWHITE}        CREATE VLESS ACCOUNT       ${NC}"
  echo -e " ${NC} ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo "  A client with the specified name was already created, please choose another name."
  echo ""
  echo -e " ${NC} ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  read -n 1 -s -r -p "  Press Any Key To Back On Menu"
  m-vless
fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p " Masa Aktif : " masaaktif
read -p " Batas Kuota : " Quota
read -p " Batas IP : " iplimit
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email" : "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email" : "'""$user""'"' /etc/xray/config.json

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
clear
cat >/var/www/html/vless-$user.txt <<-END
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Format VLESS For Clash
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Format Vless WS TLS
- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      ost: ${domain}

# Format Vless WS Non TLS
- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)
- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
  grpc-service-name: vless-grpc
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Link Akun Vless 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Link TLS      : 
${vlesslink1}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Link none TLS : 
${vlesslink2}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Link GRPC     : 
${vlesslink3}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


END

systemctl restart xray
systemctl restart nginx
clear
echo -e ""
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» INFORMASI AKUN « " | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Domain  : ${domain}" | tee -a /etc/user-create/user.log
echo -e "» Pengguna  : ${user}"  | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» port TLS  : 443" | tee -a /etc/user-create/user.log
#echo -e "» Port DNS  : 443" | tee -a /etc/user-create/user.log
echo -e "» Port NTLS  : 80, 8080, 8880, 2082" | tee -a /etc/user-create/user.log
echo -e "» User ID  : ${uuid}" | tee -a /etc/user-create/user.log
#echo -e "» Xray Dns.  : ${NS}" | tee -a /etc/user-create/user.log
#echo -e "» Pubkey.  : ${PUB}" | tee -a /etc/user-create/user.log
echo -e "» Encryption  : none" | tee -a /etc/user-create/user.log
echo -e "» Path TLS  : /vless/multi-path " | tee -a /etc/user-create/user.log
echo -e "» ServiceName  : vless-grpc" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» VLESS TLS" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "${vlesslink1}" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» VLESS NTLS" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "${vlesslink2}" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» VLESS GRPC" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━◈◈━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "${vlesslink3}" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo -e "» Batas Ip  : ${iplimit} Device" | tee -a /etc/user-create/user.log
echo -e "» Batas Kuota  : ${Quota} GB" | tee -a /etc/user-create/user.log
echo -e "» Aktif Selama  : $masaaktif Hari" | tee -a /etc/user-create/user.log
echo -e "» Tanggal Dibuat  : $tnggl" | tee -a /etc/user-create/user.log
echo -e "» Tanggal Exp  : $expe" | tee -a /etc/user-create/user.log
echo -e "${Lgreen}◈━━━━━━━━◈◈━━━━━━━━◈ ${NC}" | tee -a /etc/user-create/user.log
echo "" | tee -a /etc/user-create/user.log
read -p "ENTER UNTUK KEMBALI KE MENU"
menu